---
title: "Untitled"
author: "p"
date: "3/9/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
setwd("~/m")
library(lubridate)
library(tidyverse)
library(readxl)
library(dplyr)
library(xlsx)
library(arulesviz)
library(arules)
library(lattice)

```

```{r}
data <- read_xlsx("sundata.xlsx")
View(data)
str(data)
summary(data)
```

```{r}
data$Date <- ymd(data$Date)
data$Day <- wday(data$Date, label = T)

# Get column names
colnames(data)
data1 <- data[, c(1,13,2,3,4,5,6,7,8,9,10,11,12)]
data1

# Set factors
cols <- c("Date","Transaction","CategoryID","Category", "ClassID","Class", "ID","Menu","Day")
sun <-data1 %>% mutate_at(cols, factor)
head(sun)
sun$Day <- as.factor(sun$Day)
summary(sun)

# split txn
sun.agg <- split(sun$Menu, sun$Transaction)
head(sun.agg)

class(sun.agg)
sun.agg

# remove dupes in each txn
sun.agg1 <- list()
 for (i in 1:length(sun.agg)) {
   sun.agg1[[i]] <- as.character(sun.agg[[i]][!duplicated(sun.agg[[i]])])
 }


```

